name: Build and Push Docker image to GHCR and Deploy on EC2
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker build \
            -t ${{ env.REGISTRY }}/$IMAGE_LOWER:latest \
            -t ${{ env.REGISTRY }}/$IMAGE_LOWER:${{ github.sha }} \
            -f ./Dockerfile .

      - name: Push Docker image
        run: |
          IMAGE_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker push ${{ env.REGISTRY }}/$IMAGE_LOWER:latest
          docker push ${{ env.REGISTRY }}/$IMAGE_LOWER:${{ github.sha }}        
  deploy-to-ec2:
   needs: build-and-push
   runs-on: ubuntu-latest

   steps:
    - name: Deploy to EC2 via SSH 
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

        REPO_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')  
        ACTOR_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        FULL_IMAGE_NAME="${{ env.REGISTRY }}/$REPO_LOWER:latest"
        EC2_TARGET="$"{{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}""

        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | ssh -i ~/.ssh/ec2_key.pem $EC2_TARGET "docker login ${{ env.REGISTRY }} -u $ACTOR_LOWER --password-stdin"

        ssh -i ~/.ssh/ec2_key.pem $EC2_TARGET "docker pull $FULL_IMAGE_NAME"
        ssh -i ~/.ssh/ec2_key.pem $EC2_TARGET "docker run -d --name my-app-conatiner --restart my-app-conatiner --network host $FULL_IMAGE_NAME"
        
        docker ps -a 
        docker images 

        ssh -i ~/.ssh/ec2_key.pem $EC2_TARGET "docker system prune -f" 

      

